version: "3.8"

services:
  app:
    container_name: application
    build: .
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:14-alpine
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dnarna
      - POSTGRES_PASSWORD=dnarna

volumes:
  postgres_data: